version: "3.9"
services:
  db:
    container_name: db
    build:
      context: ./build/db
      dockerfile: Dockerfile
      target: dev
    # platform: linux/x86_64 // add this for Apple Silicon
    tty: true
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./build/db/init:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
      # - type: volume
      #   source: db
      #   target: /var/lib/mysql
      # - type: bind
      #   source: ./build/db/init
      #   target: /docker-entrypoint-initdb.d
    networks:
      - golang_test_network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=${MYSQL_HOST}
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    links:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
    # volumes:
    #   - type: volume
    #     source: sessions
    #     target: /sessions
    #     volume:
    #       nocopy: true
    networks:
      - golang_test_network

  api:
    container_name: api
    build:
      context: ./build/api
      dockerfile: Dockerfile
      target: dev
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - .:/go/src/app
    env_file:
      - .env
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - ${MYSQL_HOST}
    networks:
      - golang_test_network

# volumes:
#   db:
#     name: db-volume
  # sessions:
  #   name: phpmyadmin-volume

networks:
  golang_test_network:
    external: true
