name: ci
on:
 push:
  branches:
    - "**"
  pull_request: {}
jobs:
  test:
     runs-on: ubunth-latest

     steps:
      - name: setup go
        use: actions/setup-go@v2
        with:
          go-versionL 1.x
      
      - name: checkout
        use: actions/checkout@v2
      
      - name: golangci-lint
        use: golangci/golangci-lint-actions@v2
        with:
          version: v1.44.2
          args: --disable-all --enable=govet, errcjeck, staticcheck, gosimple
      
      - name: test
        run: go test -v ./...
